
class FoodModel {
  final String image;
  final String title;
  final String time;
  final String rating;
  final String location;
  final String distance;
  final String discount;
  final String numofrating;
  final String price;
  final String deliveryfee;
  final List<String> tbartext;

  FoodModel(
      {required this.image,
      required this.title,
      required this.rating,
      required this.time,
      required this.location,
      required this.distance,
      required this.discount,
      required this.numofrating,
      required this.price,
      required this.deliveryfee,
      required this.tbartext});
}

// List<FoodModel> myfood = [
//   FoodModel(
//     image: AppImages.award,
//     title: "Barbar",
//     rating: "4.3",
//     time: "55-65 mins",
//     location: "Labanese Shawarma",
//     distance: "3.1 km",
//     discount: "Crazy Deal: 50% off",
//     numofrating: "999+",
//     price: "\$\$\$",
//     deliveryfee: "AED 7.50",
//     tbartext: [
//       "Bestsellers 🔥",
//       "Businesses Lunch",
//       "Healthy Meals",
//       "Gathering Box",
//       "Break Fast",
//     ],
//   ),
//   FoodModel(
//     image: AppImages.award,
//     title: "Sushi",
//     rating: "4.7",
//     time: "55-65 mins",
//     location: "Labanese Asian, sushi",
//     distance: "3.3 km",
//     discount: "Crazy Deal: 50% off",
//     numofrating: "509+",
//     price: "\$\$\$",
//     deliveryfee: "AED 7.50",
//     tbartext: [
//       "Bestsellers 🔥",
//       "Sushi Cago Signature",
//       "Authentic Boxes",
//       "Miami Boxes",
//       "Salmon Boxes",
//     ],
//   ),
//   FoodModel(
//     image: AppImages.award,
//     title: "Kaak Al Manara",
//     rating: "4.6",
//     time: "55-65 mins",
//     location: "Labanese Aribic, Manakish",
//     distance: "2.6 km",
//     discount: "Crazy Deal: 50% off",
//     numofrating: "700+",
//     price: "\$\$\$",
//     deliveryfee: "AED 7.50",
//     tbartext: [
//       "Bestsellers 🔥",
//       "New: Party Boxes Sliders",
//       "New: Kid's Meal",
//       "Break Fast",
//       "The Bakery by Ka'ak Al Manara-Mouajanat",
//     ],
//   ),
//   FoodModel(
//     image: AppImages.award,
//     title: "Crepe & Go",
//     rating: "4.3",
//     time: "55-65 mins",
//     location: "Desert, Crepes",
//     distance: "3.1 km",
//     discount: "Crazy Deal: 50% off",
//     numofrating: "999+",
//     price: "\$\$\$",
//     deliveryfee: "AED 7.50",
//     tbartext: [
//       "Bestsellers 🔥",
//       "Dubai Famous Kunafa",
//       "Crepes",
//       "Create your own",
//       "Signature Creps",
//     ],
//   ),
//   FoodModel(
//       image: AppImages.award,
//       title: "Mumbai Junction vegetarian Restaurant",
//       rating: "4.3",
//       time: "55-65 mins",
//       location: "Indian, north indian, Rice ",
//       distance: "3.1 km",
//       discount: "Crazy Deal: 50% off",
//       numofrating: "999+",
//       price: "\$\$\$",
//       deliveryfee: "AED 7.50",
//       tbartext: [
//         "Bestsellers 🔥",
//         "Authentic Indian Sweets ",
//         "Mj Combo & Thali",
//         "Mubbai Street Specialty",
//         "Starter",
//       ]),
//   FoodModel(
//       image: AppImages.award,
//       title: "Firehouse Subs",
//       rating: "4.3",
//       time: "55-65 mins",
//       location: "Snadwiches, Snacks",
//       distance: "3.1 km",
//       discount: "Crazy Deal: 50% off",
//       numofrating: "999+",
//       price: "\$\$\$",
//       deliveryfee: "AED 7.50",
//       tbartext: [
//         "Bestsellers 🔥",
//         "Cream Exclusive Meal",
//         "Combo Value Meal",
//         "12 inch Meal",
//         "8 inch Meal",
//       ]),
//   FoodModel(
//       image: AppImages.award,
//       title: "Maestro Pizza",
//       rating: "4.3",
//       time: "55-65 mins",
//       location: "Italian, Pizza",
//       distance: "3.1 km",
//       discount: "Crazy Deal: 50% off",
//       numofrating: "999+",
//       price: "\$\$\$",
//       deliveryfee: "AED 7.50",
//       tbartext: [
//         "Bestsellers 🔥",
//         "Taste of the world",
//         "Chef s Selection Medium",
//         "The original Small",
//         "The Orignal Medium",
//       ]),
//   FoodModel(
//       image: AppImages.award,
//       title: "Right Bite",
//       rating: "4.3",
//       time: "55-65 mins",
//       location: "Healthy, Breakfast",
//       distance: "3.1 km",
//       discount: "Crazy Deal: 50% off",
//       numofrating: "999+",
//       price: "\$\$\$",
//       deliveryfee: "AED 7.50",
//       tbartext: [
//         "Bestsellers 🔥",
//         "30 % Off",
//         "New Burgers",
//         "New Protein Packed 💪",
//         "Power Bowls",
//       ]),
//   FoodModel(
//       image: AppImages.award,
//       title: "Laffah Restaurant",
//       rating: "4.3",
//       time: "55-65 mins",
//       location: "Lebbanes,BBQ & Grill, Sharwarma",
//       distance: "3.1 km",
//       discount: "Crazy Deal: 50% off",
//       numofrating: "999+",
//       price: "\$\$\$",
//       deliveryfee: "AED 7.50",
//       tbartext: [
//         "Bestsellers 🔥",
//         "Shawarma Sandwiches",
//         "Shawarma",
//         "Broasted",
//         "Patato",
//       ]),
//   FoodModel(
//       image: AppImages.award,
//       title: "Mumbai Spices",
//       rating: "4.3",
//       time: "55-65 mins",
//       location: " Indian, North Indian, Biryani",
//       distance: "3.1 km",
//       discount: "Crazy Deal: 50% off",
//       numofrating: "999+",
//       price: "\$\$\$",
//       deliveryfee: "AED 7.50",
//       tbartext: [
//         "Bestsellers 🔥",
//         "Rice & Bryani",
//         "Thali",
//         "Mumbai Chinese",
//         "Chaat & Pav Snacks",
//       ]),
// ];

List<FoodModel> myfood = [
  FoodModel(
    image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFq1jBrOu_6HA0OS_65_A8GPo5n0pwiZwbjw&s',
    title: "BarBeQ",
    rating: "4.3",
    time: "55-65 mins",
    location: "Labanese Shawarma",
    distance: "3.1 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "999+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Businesses Lunch",
      "Healthy Meals",
      "Gathering Box",
      "Break Fast",
    ],
  ),
  FoodModel(
    image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBujsweOvUURzpliWA3J1xTBxkUGPWzBcnKeJ3nRtsI1tDdv9W7JXIuM7SjJ4oIG9Uylw&usqp=CAU',
    title: "Lasania Hub",
    rating: "4.7",
    time: "55-65 mins",
    location: "Labanese Asian, sushi",
    distance: "3.3 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "509+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Sushi Cago Signature",
      "Authentic Boxes",
      "Miami Boxes",
      "Salmon Boxes",
    ],
  ),
  FoodModel(
    image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9pGj4j-Ih7yUz0p4BRiMalRNH5ALR5G7s8A&s',
    title: "KebabChi",
    rating: "4.6",
    time: "55-65 mins",
    location: "Labanese Aribic, Manakish",
    distance: "2.6 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "700+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "New: Party Boxes Sliders",
      "New: Kid's Meal",
      "Break Fast",
      "The Bakery by Ka'ak Al Manara-Mouajanat",
    ],
  ),
  FoodModel(
    image:
        'https://media.istockphoto.com/id/1403657533/photo/small-outdoor-caf%C3%A9.jpg?s=612x612&w=0&k=20&c=Ao20CoCC_T-PJTzBDcptG7yho8Flnj-NPhO6jLgyep8=',
    title: "La Bequet",
    rating: "4.3",
    time: "55-65 mins",
    location: "Desert, Crepes",
    distance: "3.1 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "999+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Dubai Famous Kunafa",
      "Crepes",
      "Create your own",
      "Signature Creps",
    ],
  ),
  FoodModel(
      image:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsy5ZBbucwY5XFLqo_wlVUcWwnjqIq3uUhg&s',
      title: "Eeetwell",
      rating: "4.3",
      time: "55-65 mins",
      location: "Indian, north indian, Rice ",
      distance: "3.1 km",
      discount: "Crazy Deal: 50% off",
      numofrating: "999+",
      price: "\$\$\$",
      deliveryfee: "AED 7.50",
      tbartext: [
        "Bestsellers 🔥",
        "Authentic Indian Sweets ",
        "Mj Combo & Thali",
        "Mubbai Street Specialty",
        "Starter",
      ]),
  FoodModel(
      image:
          'https://media.post.rvohealth.io/wp-content/uploads/2021/07/Starbucks_Food_Spinach_Feta_Wrap-732x549-thumbnail-732x549.jpg',
      title: "Yo!-Sushi",
      rating: "4.3",
      time: "55-65 mins",
      location: "Snadwiches, Snacks",
      distance: "3.1 km",
      discount: "Crazy Deal: 50% off",
      numofrating: "999+",
      price: "\$\$\$",
      deliveryfee: "AED 7.50",
      tbartext: [
        "Bestsellers 🔥",
        "Cream Exclusive Meal",
        "Combo Value Meal",
        "12 inch Meal",
        "8 inch Meal",
      ]),
];

List<FoodModel> popularBrands = [
  FoodModel(
    image:
        'https://logos-world.net/wp-content/uploads/2020/04/McDonalds-Logo.png',
    title: "Mc Donald",
    rating: "4.3",
    time: "55-65 mins",
    location: "Labanese Shawarma",
    distance: "3.1 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "999+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Businesses Lunch",
      "Healthy Meals",
      "Gathering Box",
      "Break Fast",
    ],
  ),
  FoodModel(
    image:
        'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2a/cf/b9/28/cheezious-pizza.jpg?w=900&h=500&s=1',
    title: "Chezzious",
    rating: "4.7",
    time: "55-65 mins",
    location: "Labanese Asian, sushi",
    distance: "3.3 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "509+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Sushi Cago Signature",
      "Authentic Boxes",
      "Miami Boxes",
      "Salmon Boxes",
    ],
  ),
  FoodModel(
    image:
        'https://play-lh.googleusercontent.com/qR-sPEGkCQvborNj2jqOF00EV3N9vxJMXYwaufVQMnIspanioOVOqLUSB4kLOkzKYJE7=w600-h300-pc0xffffff-pd',
    title: "KFC",
    rating: "4.6",
    time: "55-65 mins",
    location: "Labanese Aribic, Manakish",
    distance: "2.6 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "700+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "New: Party Boxes Sliders",
      "New: Kid's Meal",
      "Break Fast",
      "The Bakery by Ka'ak Al Manara-Mouajanat",
    ],
  ),
  FoodModel(
    image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4mn74PTlVHE-UElXmyr5dVzzs8X4MDG8pzQ&s',
    title: "SUBWAY",
    rating: "4.3",
    time: "55-65 mins",
    location: "Desert, Crepes",
    distance: "3.1 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "999+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Dubai Famous Kunafa",
      "Crepes",
      "Create your own",
      "Signature Creps",
    ],
  ),
  FoodModel(
      image:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsy5ZBbucwY5XFLqo_wlVUcWwnjqIq3uUhg&s',
      title: "Eeetwell",
      rating: "4.3",
      time: "55-65 mins",
      location: "Indian, north indian, Rice ",
      distance: "3.1 km",
      discount: "Crazy Deal: 50% off",
      numofrating: "999+",
      price: "\$\$\$",
      deliveryfee: "AED 7.50",
      tbartext: [
        "Bestsellers 🔥",
        "Authentic Indian Sweets ",
        "Mj Combo & Thali",
        "Mubbai Street Specialty",
        "Starter",
      ]),
  FoodModel(
      image:
          'https://media.post.rvohealth.io/wp-content/uploads/2021/07/Starbucks_Food_Spinach_Feta_Wrap-732x549-thumbnail-732x549.jpg',
      title: "Yo!-Sushi",
      rating: "4.3",
      time: "55-65 mins",
      location: "Snadwiches, Snacks",
      distance: "3.1 km",
      discount: "Crazy Deal: 50% off",
      numofrating: "999+",
      price: "\$\$\$",
      deliveryfee: "AED 7.50",
      tbartext: [
        "Bestsellers 🔥",
        "Cream Exclusive Meal",
        "Combo Value Meal",
        "12 inch Meal",
        "8 inch Meal",
      ]),
];
List<FoodModel> nearby = [
  FoodModel(
    image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsy5ZBbucwY5XFLqo_wlVUcWwnjqIq3uUhg&s',
    title: "Kebabish Grill",
    rating: "4.3",
    time: "55-65 mins",
    location: "Labanese Shawarma",
    distance: "3.1 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "999+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Businesses Lunch",
      "Healthy Meals",
      "Gathering Box",
      "Break Fast",
    ],
  ),
  FoodModel(
    image:
        'https://media.post.rvohealth.io/wp-content/uploads/2021/07/Starbucks_Food_Spinach_Feta_Wrap-732x549-thumbnail-732x549.jpg',
    title: "Fast Food",
    rating: "4.7",
    time: "55-65 mins",
    location: "Labanese Asian, sushi",
    distance: "3.3 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "509+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Sushi Cago Signature",
      "Authentic Boxes",
      "Miami Boxes",
      "Salmon Boxes",
    ],
  ),
  FoodModel(
    image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPIVQ3-mRyGlCWo38s2i1JFRdaABZqKpbgpA&s',
    title: "Pizza Hub",
    rating: "4.6",
    time: "55-65 mins",
    location: "Labanese Aribic,",
    distance: "2.6 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "700+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "New: Party Boxes Sliders",
      "New: Kid's Meal",
      "Break Fast",
      "The Bakery by Ka'ak Al Manara-Mouajanat",
    ],
  ),
  FoodModel(
    image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Pani_Puri1.JPG/960px-Pani_Puri1.JPG',
    title: "Pani Puri ",
    rating: "4.3",
    time: "55-65 mins",
    location: "Desert, Crepes",
    distance: "3.1 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "999+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Dubai Famous Kunafa",
      "Crepes",
      "Create your own",
      "Signature Creps",
    ],
  ),
  FoodModel(
      image:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsy5ZBbucwY5XFLqo_wlVUcWwnjqIq3uUhg&s',
      title: "Eeetwell",
      rating: "4.3",
      time: "55-65 mins",
      location: "Indian, north indian, Rice ",
      distance: "3.1 km",
      discount: "Crazy Deal: 50% off",
      numofrating: "999+",
      price: "\$\$\$",
      deliveryfee: "AED 7.50",
      tbartext: [
        "Bestsellers 🔥",
        "Authentic Indian Sweets ",
        "Mj Combo & Thali",
        "Mubbai Street Specialty",
        "Starter",
      ]),
  FoodModel(
      image:
          'https://media.post.rvohealth.io/wp-content/uploads/2021/07/Starbucks_Food_Spinach_Feta_Wrap-732x549-thumbnail-732x549.jpg',
      title: "Yo!-Sushi",
      rating: "4.3",
      time: "55-65 mins",
      location: "Snadwiches, Snacks",
      distance: "3.1 km",
      discount: "Crazy Deal: 50% off",
      numofrating: "999+",
      price: "\$\$\$",
      deliveryfee: "AED 7.50",
      tbartext: [
        "Bestsellers 🔥",
        "Cream Exclusive Meal",
        "Combo Value Meal",
        "12 inch Meal",
        "8 inch Meal",
      ]),
];
List<FoodModel> bestSeller = [
  FoodModel(
    image: 'https://images.deliveryhero.io/image/fd-pk/LH/b497-listing.jpg',
    title: "Kebabish Grill",
    rating: "4.3",
    time: "55-65 mins",
    location: "Labanese Shawarma",
    distance: "3.1 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "999+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Businesses Lunch",
      "Healthy Meals",
      "Gathering Box",
      "Break Fast",
    ],
  ),
  FoodModel(
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPIVQ3-mRyGlCWo38s2i1JFRdaABZqKpbgpA&s',
    title: "Fast Food",
    rating: "4.7",
    time: "55-65 mins",
    location: "Labanese Asian, sushi",
    distance: "3.3 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "509+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Sushi Cago Signature",
      "Authentic Boxes",
      "Miami Boxes",
      "Salmon Boxes",
    ],
  ),
  FoodModel(
    image:
        'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPIVQ3-mRyGlCWo38s2i1JFRdaABZqKpbgpA&s',
    title: "Pizza Hub",
    rating: "4.6",
    time: "55-65 mins",
    location: "Labanese Aribic,",
    distance: "2.6 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "700+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "New: Party Boxes Sliders",
      "New: Kid's Meal",
      "Break Fast",
      "The Bakery by Ka'ak Al Manara-Mouajanat",
    ],
  ),
  FoodModel(
    image:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Pani_Puri1.JPG/960px-Pani_Puri1.JPG',
    title: "Pani Puri ",
    rating: "4.3",
    time: "55-65 mins",
    location: "Desert, Crepes",
    distance: "3.1 km",
    discount: "Crazy Deal: 50% off",
    numofrating: "999+",
    price: "\$\$\$",
    deliveryfee: "AED 7.50",
    tbartext: [
      "Bestsellers 🔥",
      "Dubai Famous Kunafa",
      "Crepes",
      "Create your own",
      "Signature Creps",
    ],
  ),
  FoodModel(
      image:
          'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtsy5ZBbucwY5XFLqo_wlVUcWwnjqIq3uUhg&s',
      title: "Eeetwell",
      rating: "4.3",
      time: "55-65 mins",
      location: "Indian, north indian, Rice ",
      distance: "3.1 km",
      discount: "Crazy Deal: 50% off",
      numofrating: "999+",
      price: "\$\$\$",
      deliveryfee: "AED 7.50",
      tbartext: [
        "Bestsellers 🔥",
        "Authentic Indian Sweets ",
        "Mj Combo & Thali",
        "Mubbai Street Specialty",
        "Starter",
      ]),
  FoodModel(
      image:
          'https://media.post.rvohealth.io/wp-content/uploads/2021/07/Starbucks_Food_Spinach_Feta_Wrap-732x549-thumbnail-732x549.jpg',
      title: "Yo!-Sushi",
      rating: "4.3",
      time: "55-65 mins",
      location: "Snadwiches, Snacks",
      distance: "3.1 km",
      discount: "Crazy Deal: 50% off",
      numofrating: "999+",
      price: "\$\$\$",
      deliveryfee: "AED 7.50",
      tbartext: [
        "Bestsellers 🔥",
        "Cream Exclusive Meal",
        "Combo Value Meal",
        "12 inch Meal",
        "8 inch Meal",
      ]),
];
