// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfIqnFpkOslgs2FR6MzRQC2kfPLb0QbQ0',
    appId: '1:448947898109:android:79cd3f03d6dfda1920e094',
    messagingSenderId: '448947898109',
    projectId: 'ride-e341a',
    databaseURL: 'https://ride-e341a-default-rtdb.firebaseio.com',
    storageBucket: 'ride-e341a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9RQXA_aTab-mVewsDQXgJ6vZ25JsABWU',
    appId: '1:448947898109:ios:6ce951203877106420e094',
    messagingSenderId: '448947898109',
    projectId: 'ride-e341a',
    databaseURL: 'https://ride-e341a-default-rtdb.firebaseio.com',
    storageBucket: 'ride-e341a.firebasestorage.app',
    androidClientId: '448947898109-e3v8csphurrhmce58j5lo87juqqri0rq.apps.googleusercontent.com',
    iosClientId: '448947898109-te5r1qcveeg8vqble8344k9c14po2j86.apps.googleusercontent.com',
    iosBundleId: 'com.multiservice.supr',
  );
}
